### ISSUE TITLE
Bug fixes before the firstsemester week

### ISSUE THREAD

**Issue by simonostendorf** [FHA-FB5/discordbot#115]
- [x] Selektieren der Erstsemester: Suche in der Datenbank liefert [] (siehe commands/selectFirstSemester.ts)
- [x] Alle Studiengänge sollen gelöscht werden, wenn ein neuer ausgewählt wird, dies klappt aber noch nicht (selectMenu/studyProgram.ts)

**Comment by TitusKirch** [comment]
- [ ] Error when command files not exist
